version: '3.8'

services:
  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./definitions.json:/etc/rabbitmq/definitions.json
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit load_definitions '/etc/rabbitmq/definitions.json'"
  postgres:
    image: postgres:latest
    container_name: weather_postgres
    environment:
      POSTGRES_USER: weather_admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weather_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: weather_redis
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
